/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Decimal = ColumnType<string, number | string>;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = ColumnType<JsonValue, string, string>;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface AcademicRiskScores {
  calculado_en: Generated<string>;
  created_at: string | null;
  dim_academico: Generated<Decimal>;
  dim_asistencia: Generated<Decimal>;
  dim_disciplina: Generated<Decimal>;
  dim_tendencia: Generated<Decimal>;
  estudiante_id: number;
  faltas_graves: Generated<number>;
  faltas_leves: Generated<number>;
  id: Generated<number>;
  materias_en_riesgo: Generated<number>;
  nivel: Generated<"alto" | "bajo" | "critico" | "moderado" | "sin_riesgo">;
  pct_asistencia: Decimal | null;
  promedio_general: Decimal | null;
  school_year_id: number;
  score: Generated<number>;
  suspensiones: Generated<number>;
  tardanzas: Generated<number>;
  tenant_id: number;
  total_materias: Generated<number>;
  updated_at: string | null;
}

export interface ActivityLogs {
  accion: string;
  created_at: string | null;
  descripcion: string | null;
  id: Generated<number>;
  ip: string | null;
  modelo: string | null;
  modelo_id: number | null;
  tenant_id: Generated<number>;
  user_agent: string | null;
  user_id: number | null;
}

export interface AcuerdosReunion {
  created_at: string | null;
  cumplido: Generated<number>;
  descripcion: string;
  fecha_limite: string | null;
  id: Generated<number>;
  responsable: string | null;
  reunion_id: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface Albumes {
  activo: Generated<number>;
  created_at: string | null;
  descripcion: string | null;
  id: Generated<number>;
  mostrar_en_sitio: Generated<number>;
  orden: Generated<number>;
  portada: string | null;
  tenant_id: Generated<number>;
  titulo: string;
  updated_at: string | null;
}

export interface AlertasSistema {
  creado_por: number | null;
  created_at: string | null;
  destinatario_id: number | null;
  destinatario_rol: string | null;
  expira_en: string | null;
  fecha_leida: string | null;
  id: Generated<number>;
  leida: Generated<number>;
  mensaje: string;
  nivel: Generated<"danger" | "info" | "success" | "warning">;
  referencia_id: number | null;
  referencia_tipo: string | null;
  school_year_id: number | null;
  tenant_id: Generated<number>;
  tipo: Generated<"baja_asistencia" | "entrega_notas" | "evento_calendario" | "otro" | "periodo_cierre" | "riesgo_academico">;
  titulo: string;
  updated_at: string | null;
}

export interface ArchivosEntrega {
  created_at: string | null;
  entrega_id: number;
  id: Generated<number>;
  nombre_original: string;
  ruta: string;
  tamanio: Generated<number>;
  tenant_id: Generated<number>;
  tipo_mime: string;
  updated_at: string | null;
}

export interface ArchivosMaterial {
  created_at: string | null;
  id: Generated<number>;
  material_id: number;
  nombre_original: string;
  ruta: string;
  tenant_id: Generated<number>;
  tipo_mime: string;
  updated_at: string | null;
}

export interface Areas {
  activo: Generated<number>;
  ciclo: Generated<"ambos" | "primer_ciclo" | "segundo_ciclo">;
  color: Generated<string>;
  created_at: string | null;
  id: Generated<number>;
  nombre: string;
  tenant_id: Generated<number>;
  tipo: Generated<"academica" | "ambas" | "tecnica">;
  updated_at: string | null;
}

export interface AreasTecnicas {
  activo: Generated<number>;
  codigo: string | null;
  color: Generated<string>;
  created_at: string | null;
  descripcion: string | null;
  id: Generated<number>;
  nombre: string;
  orden: Generated<number>;
  tenant_id: number;
  updated_at: string | null;
}

export interface ArticulosInventario {
  cantidad_disponible: Generated<number>;
  cantidad_total: Generated<number>;
  categoria: Generated<"deportivo" | "limpieza" | "material_didactico" | "mobiliario" | "otro" | "tecnologia">;
  costo_unitario: Decimal | null;
  created_at: string | null;
  descripcion: string | null;
  estado: Generated<"bueno" | "malo" | "regular" | "reparacion">;
  id: Generated<number>;
  nombre: string;
  tenant_id: Generated<number>;
  ubicacion: string | null;
  updated_at: string | null;
}

export interface Asignaciones {
  activo: Generated<number>;
  area: Generated<"academica" | "tecnica">;
  asignatura_id: number;
  created_at: string | null;
  docente_id: number | null;
  grupo_id: number;
  horas_semana: Generated<number>;
  id: Generated<number>;
  pesos_ra: Json | null;
  school_year_id: number;
  tenant_id: Generated<number>;
  tipo_evaluacion: Generated<"competencias" | "componentes" | "indicadores_logro" | "ra">;
  updated_at: string | null;
}

export interface Asignaturas {
  activo: Generated<number>;
  area: string | null;
  area_id: number | null;
  codigo: string;
  color: Generated<string>;
  created_at: string | null;
  descripcion: string | null;
  es_basica: Generated<number>;
  familia_id: number | null;
  horas_semanales: Generated<number>;
  id: Generated<number>;
  nombre: string;
  /**
   * 0 = componentes tradicionales, >0 = cantidad de RA para área técnica
   */
  num_ra: Generated<number>;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface Asistencias {
  asignacion_id: number;
  created_at: string | null;
  estado: Generated<"ausente" | "excusa" | "presente" | "retiro" | "tarde">;
  fecha: string;
  id: Generated<number>;
  justificacion: string | null;
  justificacion_tipo: string | null;
  matricula_id: number;
  registrado_por: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface Aulas {
  capacidad: Generated<number>;
  centro_id: number | null;
  codigo: string | null;
  created_at: string | null;
  deleted_at: string | null;
  disponible: Generated<number>;
  equipamiento: Json | null;
  id: Generated<number>;
  nombre: string;
  piso: string | null;
  tenant_id: Generated<number>;
  tipo: Generated<"aula" | "biblioteca" | "gimnasio" | "laboratorio" | "taller">;
  updated_at: string | null;
}

export interface AvisosEmergencia {
  created_at: string | null;
  destinatarios: Generated<"docentes" | "grupo" | "padres" | "todos">;
  enviado_por_id: number;
  grupo_id: number | null;
  id: Generated<number>;
  mensaje: string;
  tenant_id: Generated<number>;
  tipo: Generated<"actividad" | "emergencia" | "informativo" | "suspension">;
  titulo: string;
  total_enviados: Generated<number>;
  updated_at: string | null;
}

export interface BackupRuns {
  archivos_archivo: string | null;
  archivos_tamano_bytes: number | null;
  bd_archivo: string | null;
  bd_tamano_bytes: number | null;
  created_at: string | null;
  duracion_segundos: number | null;
  eliminados_retencion: Generated<number>;
  error_mensaje: string | null;
  estado: Generated<"exitoso" | "fallido">;
  etapa_fallo: string | null;
  finalizado_en: string | null;
  id: Generated<number>;
  iniciado_en: string;
  updated_at: string | null;
}

export interface BancoPreguntas {
  asignatura_id: number | null;
  categoria: string | null;
  created_at: string | null;
  docente_id: number;
  enunciado: string;
  explicacion: string | null;
  id: Generated<number>;
  opciones: Json | null;
  puntos_default: Generated<Decimal>;
  tenant_id: number;
  tipo: Generated<"abierta" | "multiple" | "verdadero_falso">;
  updated_at: string | null;
  usos: Generated<number>;
}

export interface Becas {
  activo: Generated<number>;
  created_at: string | null;
  criterio: string | null;
  descripcion: string | null;
  id: Generated<number>;
  nombre: string;
  tenant_id: Generated<number>;
  tipo: "monto_fijo" | "porcentaje";
  updated_at: string | null;
  valor: Decimal;
}

export interface BecasEstudiante {
  activo: Generated<number>;
  beca_id: number;
  created_at: string | null;
  fecha_fin: string | null;
  fecha_inicio: string;
  id: Generated<number>;
  matricula_id: number;
  notas: string | null;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface BoletinesConfig {
  bloquear_por_deuda: Generated<number>;
  codigo: string | null;
  color_primario: Generated<string>;
  color_secundario: Generated<string>;
  created_at: string | null;
  direccion: string | null;
  director: string | null;
  distrito: string | null;
  encargado_academico: string | null;
  id: Generated<number>;
  lema: string | null;
  logo: string | null;
  logo_alto: Generated<number>;
  logo_ancho: Generated<number>;
  mostrar_asistencia: Generated<number>;
  mostrar_foto_estudiante: Generated<number>;
  mostrar_indicadores: Generated<number>;
  municipio: string | null;
  nivel_educativo: string | null;
  nombre_institucion: string | null;
  observaciones_generales: string | null;
  pie_pagina: string | null;
  regional: string | null;
  school_year_id: number;
  tamano_fuente: Generated<string>;
  telefono: string | null;
  tenant_id: Generated<number>;
  titulo_director: string | null;
  titulo_encargado: string | null;
  updated_at: string | null;
}

export interface BoletinObservaciones {
  contenido: string;
  created_at: string | null;
  docente_id: number | null;
  id: Generated<number>;
  matricula_id: number;
  periodo_id: number | null;
  school_year_id: number;
  tenant_id: Generated<number>;
  tipo: Generated<"academica" | "conducta" | "general" | "sugerencia">;
  updated_at: string | null;
}

export interface Cache {
  expiration: number;
  key: string;
  value: string;
}

export interface CacheLocks {
  expiration: number;
  key: string;
  owner: string;
}

export interface CalendarioAcademico {
  activo: Generated<number>;
  aplica_a: Generated<"administrativos" | "coordinadores" | "docentes" | "estudiantes" | "todos">;
  color: Generated<string>;
  creado_por: number;
  created_at: string | null;
  descripcion: string | null;
  fecha_fin: string | null;
  fecha_inicio: string;
  hora_inicio: string | null;
  ics_sequence: Generated<number>;
  id: Generated<number>;
  periodo_id: number | null;
  school_year_id: number;
  tenant_id: Generated<number>;
  tipo: Generated<"actividad" | "entrega_notas" | "examen" | "feriado" | "fin_periodo" | "inicio_periodo" | "otro" | "reunion" | "suspension">;
  titulo: string;
  updated_at: string | null;
}

export interface CalendarioDestinatarios {
  calendario_id: number;
  correo_enviado_at: string | null;
  created_at: string | null;
  id: Generated<number>;
  notificado_at: string | null;
  tenant_id: number | null;
  updated_at: string | null;
  user_id: number;
}

export interface CalificacionAudits {
  asignacion_id: number;
  campo: string;
  created_at: string | null;
  id: Generated<number>;
  ip: string | null;
  matricula_id: number;
  modelo: string;
  registro_id: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
  user_id: number | null;
  valor_anterior: Decimal | null;
  valor_nuevo: Decimal | null;
}

export interface Calificaciones {
  asignacion_id: number;
  asistencia_clases: number | null;
  asistencia_total: number | null;
  created_at: string | null;
  criterios_ra: Json | null;
  examen: Decimal | null;
  id: Generated<number>;
  indicador: "Bueno" | "En proceso" | "Excelente" | "Insuficiente" | null;
  matricula_id: number;
  modificado_por: number | null;
  nota_cc: Decimal | null;
  nota_ce: Decimal | null;
  nota_completiva: Decimal | null;
  nota_extraordinaria: Decimal | null;
  nota_final: Decimal | null;
  observaciones: string | null;
  participacion: Decimal | null;
  periodo_id: number;
  practicas: Decimal | null;
  proyecto: Decimal | null;
  publicado: Generated<number>;
  ra1: Decimal | null;
  ra10: Decimal | null;
  ra2: Decimal | null;
  ra3: Decimal | null;
  ra4: Decimal | null;
  ra5: Decimal | null;
  ra6: Decimal | null;
  ra7: Decimal | null;
  ra8: Decimal | null;
  ra9: Decimal | null;
  /**
   * JSON: {"1":[null,82,null],"2":[75,null,null]} — 3 recuperaciones por RA
   */
  recuperaciones_ra: Json | null;
  tareas: Decimal | null;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface CalificacionesAcademicas {
  asignacion_id: number;
  asist_p1: number | null;
  asist_p2: number | null;
  asist_p3: number | null;
  asist_p4: number | null;
  avg_comp1_p1: Decimal | null;
  avg_comp1_p2: Decimal | null;
  avg_comp1_p3: Decimal | null;
  avg_comp1_p4: Decimal | null;
  avg_comp2_p1: Decimal | null;
  avg_comp2_p2: Decimal | null;
  avg_comp2_p3: Decimal | null;
  avg_comp2_p4: Decimal | null;
  avg_comp3_p1: Decimal | null;
  avg_comp3_p2: Decimal | null;
  avg_comp3_p3: Decimal | null;
  avg_comp3_p4: Decimal | null;
  avg_comp4_p1: Decimal | null;
  avg_comp4_p2: Decimal | null;
  avg_comp4_p3: Decimal | null;
  avg_comp4_p4: Decimal | null;
  clases_p1: number | null;
  clases_p2: number | null;
  clases_p3: number | null;
  clases_p4: number | null;
  comp1_p1: Decimal | null;
  comp1_p2: Decimal | null;
  comp1_p3: Decimal | null;
  comp1_p4: Decimal | null;
  comp1_r1: Decimal | null;
  comp1_r2: Decimal | null;
  comp1_r3: Decimal | null;
  comp1_r4: Decimal | null;
  comp2_p1: Decimal | null;
  comp2_p2: Decimal | null;
  comp2_p3: Decimal | null;
  comp2_p4: Decimal | null;
  comp2_r1: Decimal | null;
  comp2_r2: Decimal | null;
  comp2_r3: Decimal | null;
  comp2_r4: Decimal | null;
  comp3_p1: Decimal | null;
  comp3_p2: Decimal | null;
  comp3_p3: Decimal | null;
  comp3_p4: Decimal | null;
  comp3_r1: Decimal | null;
  comp3_r2: Decimal | null;
  comp3_r3: Decimal | null;
  comp3_r4: Decimal | null;
  comp4_p1: Decimal | null;
  comp4_p2: Decimal | null;
  comp4_p3: Decimal | null;
  comp4_p4: Decimal | null;
  comp4_r1: Decimal | null;
  comp4_r2: Decimal | null;
  comp4_r3: Decimal | null;
  comp4_r4: Decimal | null;
  created_at: string | null;
  eval_ce: Decimal | null;
  eval_cf: Decimal | null;
  id: Generated<number>;
  indicador: "Bueno" | "En proceso" | "Excelente" | "Insuficiente" | null;
  matricula_id: number;
  modificado_por: number | null;
  nota_cc: Decimal | null;
  nota_ce: Decimal | null;
  nota_completiva: Decimal | null;
  nota_extraordinaria: Decimal | null;
  nota_final: Decimal | null;
  observaciones: string | null;
  pct_asistencia: Decimal | null;
  prom_comp1: Decimal | null;
  prom_comp2: Decimal | null;
  prom_comp3: Decimal | null;
  prom_comp4: Decimal | null;
  publicado: Generated<number>;
  recuperaciones_acad: Json | null;
  school_year_id: number;
  situacion: "A" | "R" | null;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface CapacitacionesVistas {
  contenido_id: string;
  created_at: string | null;
  id: Generated<number>;
  tenant_id: number | null;
  updated_at: string | null;
  user_id: number;
  visto_at: string;
}

export interface CarnetAccesos {
  carnet_identidad_id: number;
  created_at: string | null;
  dispositivo: string | null;
  estado: Generated<"denegado" | "presente" | "salida_anticipada" | "tardanza">;
  id: Generated<number>;
  ip_address: string | null;
  notas: string | null;
  registrado_por: number | null;
  ruta_id: number | null;
  tenant_id: number;
  tipo_evento: Generated<"biblioteca" | "bus_bajada" | "bus_subida" | "comedor" | "entrada" | "evento" | "laboratorio" | "prestamo" | "salida">;
  updated_at: string | null;
  zona_id: number | null;
}

export interface CarnetIdentidades {
  created_at: string | null;
  estado: Generated<"activo" | "suspendido" | "vencido">;
  id: Generated<number>;
  matricula_id: number | null;
  numero_carnet: string;
  qr_token: string;
  tenant_id: number;
  tipo: Generated<"docente" | "empleado" | "estudiante">;
  updated_at: string | null;
  user_id: number;
  vigencia_hasta: string | null;
}

export interface CarnetZonas {
  activo: Generated<number>;
  created_at: string | null;
  id: Generated<number>;
  nombre: string;
  tenant_id: number;
  tipo: Generated<"biblioteca" | "comedor" | "laboratorio" | "otro" | "porteria" | "salon">;
  updated_at: string | null;
}

export interface CasosSeguimiento {
  created_at: string | null;
  descripcion: string;
  estado: Generated<"abierto" | "cerrado" | "en_seguimiento">;
  estudiante_id: number;
  fecha_apertura: string;
  fecha_cierre: string | null;
  id: Generated<number>;
  nivel_riesgo: Generated<"alto" | "bajo" | "critico" | "medio">;
  responsable_id: number | null;
  tenant_id: Generated<number>;
  tipo: Generated<"academico" | "conductual" | "familiar" | "otro" | "social">;
  updated_at: string | null;
}

export interface ClasesVirtuales {
  activo: Generated<number>;
  asignacion_id: number;
  codigo_clase: string | null;
  created_at: string | null;
  descripcion: string | null;
  estudiantes_count: Generated<number>;
  id: Generated<number>;
  meeting_started_at: string | null;
  meeting_status: Generated<"active" | "idle">;
  meeting_url: string | null;
  nombre: string;
  permite_comentarios: Generated<number>;
  portada_color: Generated<string>;
  portada_imagen: string | null;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface ClassroomMessages {
  clase_virtual_id: number;
  created_at: string | null;
  fijado: Generated<number>;
  id: Generated<number>;
  mensaje: string;
  receptor_id: number | null;
  tenant_id: number;
  tipo: Generated<"general" | "privado">;
  updated_at: string | null;
  user_id: number;
}

export interface ComentariosClassroom {
  contenido: string;
  created_at: string | null;
  id: Generated<number>;
  material_id: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
  user_id: number;
}

export interface CompetenciasEspecificas {
  activo: Generated<number>;
  asignatura_id: number;
  ciclo: Generated<"primer_ciclo" | "segundo_ciclo">;
  codigo: string;
  created_at: string | null;
  descripcion: string | null;
  id: Generated<number>;
  nombre: string;
  orden: Generated<number>;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface ComunicadoLecturas {
  comunicado_id: number;
  created_at: string | null;
  id: Generated<number>;
  leido_at: string;
  tenant_id: Generated<number>;
  updated_at: string | null;
  user_id: number;
}

export interface Comunicados {
  activo: Generated<number>;
  autor_id: number;
  created_at: string | null;
  cuerpo: string;
  es_interno: Generated<number>;
  grupo_id: number | null;
  id: Generated<number>;
  published_at: string | null;
  tenant_id: Generated<number>;
  tipo_destinatarios: Generated<"coordinadores" | "docentes" | "grupo" | "todos">;
  titulo: string;
  updated_at: string | null;
}

export interface ConceptoPagos {
  activo: Generated<number>;
  created_at: string | null;
  descripcion: string | null;
  id: Generated<number>;
  monto_defecto: Decimal | null;
  nombre: string;
  tenant_id: number;
  tipo: Generated<"inscripcion" | "mensualidad" | "otro">;
  updated_at: string | null;
}

export interface ConductaRegistros {
  asignacion_id: number;
  created_at: string | null;
  id: Generated<number>;
  matricula_id: number;
  observaciones: string | null;
  orden: number | null;
  participacion: number | null;
  periodo_id: number;
  puntualidad: number | null;
  respeto: number | null;
  responsabilidad: number | null;
  tenant_id: number;
  trabajo_equipo: number | null;
  updated_at: string | null;
}

export interface ConfigCalificaciones {
  activo: Generated<number>;
  componente: "examen" | "participacion" | "practicas" | "proyecto" | "tareas";
  created_at: string | null;
  id: Generated<number>;
  peso: Decimal;
  school_year_id: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface ConfigInstitucional {
  clave: string;
  created_at: string | null;
  descripcion: string | null;
  grupo: Generated<string>;
  id: Generated<number>;
  tenant_id: Generated<number>;
  tipo: Generated<string>;
  updated_at: string | null;
  valor: string | null;
}

export interface CursosTecnicos {
  activo: Generated<number>;
  area_tecnica_id: number;
  codigo: string | null;
  created_at: string | null;
  descripcion: string | null;
  duracion_horas: number | null;
  id: Generated<number>;
  nombre: string;
  orden: Generated<number>;
  tenant_id: number;
  updated_at: string | null;
}

export interface DeviceTokens {
  created_at: string | null;
  id: Generated<number>;
  last_used_at: string | null;
  platform: Generated<string>;
  token: string;
  updated_at: string | null;
  user_id: number;
}

export interface DiarioClases {
  actividades: string | null;
  asignacion_id: number;
  asistentes: number | null;
  created_at: string | null;
  docente_id: number;
  fecha: string;
  id: Generated<number>;
  incidencias: string | null;
  observaciones: string | null;
  tema: string;
  tenant_id: number;
  updated_at: string | null;
}

export interface DisponibilidadDocente {
  created_at: string | null;
  dia: "jueves" | "lunes" | "martes" | "miercoles" | "viernes";
  disponible: Generated<number>;
  docente_id: number;
  franja_id: number;
  id: Generated<number>;
  motivo: string | null;
  school_year_id: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface DocenteEspecialidad {
  created_at: string | null;
  docente_id: number;
  es_coordinador: Generated<number>;
  especialidad_id: number;
  fecha_asignacion: string | null;
  id: Generated<number>;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface Docentes {
  apellidos: string;
  area: Generated<"academica" | "administrativa" | "ambas" | "otro" | "tecnica" | null>;
  cargo: string | null;
  cedula: string | null;
  created_at: string | null;
  deleted_at: string | null;
  direccion: string | null;
  email: string | null;
  especialidad: string | null;
  estado: Generated<"activo" | "inactivo">;
  fecha_nacimiento: string | null;
  foto: string | null;
  id: Generated<number>;
  nombres: string;
  sexo: "F" | "M" | null;
  telefono: string | null;
  tenant_id: Generated<number>;
  titulo_academico: string | null;
  updated_at: string | null;
  user_id: number | null;
}

export interface Encuestas {
  activo: Generated<number>;
  created_at: string | null;
  descripcion: string | null;
  dirigida_a: Generated<"estudiantes" | "padres" | "todos">;
  fecha_cierre: string | null;
  id: Generated<number>;
  tenant_id: Generated<number>;
  titulo: string;
  updated_at: string | null;
}

export interface EncuestasInteres {
  apellido: string;
  created_at: string | null;
  id: Generated<number>;
  ip: string | null;
  nivel_interes: Generated<number>;
  nombre: string;
  respuestas: Json;
  telefono: string;
  tipo: "administrativo" | "docente";
  updated_at: string | null;
}

export interface EntregasClassroom {
  calificacion: Decimal | null;
  comentario_docente: string | null;
  contenido: string | null;
  created_at: string | null;
  devuelta: Generated<number>;
  estado: Generated<string>;
  fecha_entrega: string | null;
  fecha_revision: string | null;
  id: Generated<number>;
  intentos: Generated<number>;
  material_id: number;
  matricula_id: number;
  retroalimentacion: string | null;
  revisado_por: number | null;
  tenant_id: Generated<number>;
  updated_at: string | null;
  url_entrega: string | null;
}

export interface EntregasTarea {
  calificacion: Decimal | null;
  created_at: string | null;
  estado: Generated<"entregada" | "pendiente" | "revisada">;
  estudiante_id: number;
  fecha_entrega: string | null;
  id: Generated<number>;
  notas_docente: string | null;
  tarea_id: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface Equipos {
  anio_adquisicion: number | null;
  codigo: string | null;
  created_at: string | null;
  descripcion: string | null;
  estado: Generated<"baja" | "disponible" | "mantenimiento" | "prestado">;
  id: Generated<number>;
  marca: string | null;
  modelo: string | null;
  nombre: string;
  tenant_id: Generated<number>;
  tipo: Generated<"camara" | "laptop" | "otro" | "proyector" | "tablet">;
  ubicacion: string | null;
  updated_at: string | null;
}

export interface EspecialidadesTecnicas {
  activo: Generated<number>;
  codigo: string;
  color: Generated<string>;
  coordinador_id: number | null;
  created_at: string | null;
  descripcion: string | null;
  icono: Generated<string>;
  id: Generated<number>;
  nombre: string;
  orden: Generated<number>;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface EstudianteRepresentante {
  created_at: string | null;
  es_principal: Generated<number>;
  estudiante_id: number;
  id: Generated<number>;
  parentesco: Generated<string>;
  representante_id: number;
  updated_at: string | null;
}

export interface Estudiantes {
  apellidos: string;
  cedula: string | null;
  created_at: string | null;
  deleted_at: string | null;
  direccion: string | null;
  email: string | null;
  estado: Generated<"activo" | "egresado" | "inactivo" | "transferido">;
  fecha_nacimiento: string | null;
  foto: string | null;
  id: Generated<number>;
  lugar_nacimiento: string | null;
  municipio: string | null;
  nacionalidad: Generated<string>;
  nombres: string;
  notas_medicas: string | null;
  numero_matricula: string;
  provincia: string | null;
  sector: string | null;
  sexo: "F" | "M";
  telefono: string | null;
  tenant_id: Generated<number>;
  tutor_nombre: string | null;
  tutor_parentesco: string | null;
  tutor_telefono: string | null;
  tutor_trabajo: string | null;
  updated_at: string | null;
  user_id: number | null;
}

export interface EstudiantesRuta {
  created_at: string | null;
  estudiante_id: number;
  id: Generated<number>;
  parada_id: number | null;
  ruta_id: number;
  tenant_id: Generated<number>;
  tipo: Generated<"ambos" | "ida" | "vuelta">;
  updated_at: string | null;
}

export interface EvaIntentos {
  created_at: string | null;
  estado: Generated<"en_curso" | "finalizado">;
  finalizado_en: string | null;
  id: Generated<number>;
  iniciado_en: string | null;
  matricula_id: number;
  puntuacion: Generated<Decimal>;
  puntuacion_max: Generated<Decimal>;
  quiz_id: number;
  respuestas: Json | null;
  tenant_id: number;
  updated_at: string | null;
}

export interface EvaluacionesDocentes {
  created_at: string | null;
  docente_id: number;
  dominio_contenido: number;
  evaluador_id: number;
  id: Generated<number>;
  metodologia: number;
  observaciones: string | null;
  periodo_evaluado: string;
  planificacion: number;
  promedio: Decimal | null;
  puntualidad: number;
  relacion_estudiantes: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface EvaluacionesIndicadores {
  created_at: string | null;
  id: Generated<number>;
  indicador_id: number;
  matricula_id: number;
  nivel: "Bueno" | "En proceso" | "Excelente" | "Insuficiente";
  periodo_id: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface EvaluacionesRegistro {
  asignacion_id: number;
  competencia_id: number | null;
  created_at: string | null;
  id: Generated<number>;
  indicador_id: number | null;
  matricula_id: number;
  nota_numerica: Decimal | null;
  periodo_id: number;
  registrado_por: number | null;
  school_year_id: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
  valor_cualitativo: number | null;
}

export interface EvaPreguntas {
  created_at: string | null;
  enunciado: string;
  explicacion: string | null;
  id: Generated<number>;
  opciones: Json | null;
  orden: Generated<number>;
  puntos: Generated<Decimal>;
  quiz_id: number;
  tenant_id: number;
  tipo: Generated<"abierta" | "multiple" | "verdadero_falso">;
  updated_at: string | null;
}

export interface EvaQuizzes {
  aleatorizar: Generated<number>;
  asignacion_id: number;
  created_at: string | null;
  disponible_desde: string | null;
  disponible_hasta: string | null;
  duracion_minutos: number | null;
  id: Generated<number>;
  instrucciones: string | null;
  intentos_max: Generated<number>;
  mostrar_resultados: Generated<number>;
  publicado: Generated<number>;
  tenant_id: number;
  titulo: string;
  updated_at: string | null;
}

export interface Eventos {
  activo: Generated<number>;
  created_at: string | null;
  cupo_maximo: number | null;
  descripcion: string | null;
  fecha_fin: string | null;
  fecha_inicio: string;
  id: Generated<number>;
  lugar: string | null;
  nombre: string;
  tenant_id: Generated<number>;
  tipo: Generated<"academico" | "cultural" | "deportivo" | "otro" | "social">;
  updated_at: string | null;
}

export interface FailedJobs {
  connection: string;
  exception: string;
  failed_at: Generated<string>;
  id: Generated<number>;
  payload: string;
  queue: string;
  uuid: string;
}

export interface FaltasDisciplinarias {
  created_at: string | null;
  descripcion: string;
  docente_id: number | null;
  estudiante_id: number;
  fecha: string;
  id: Generated<number>;
  notas_resolucion: string | null;
  resuelto: Generated<number>;
  tenant_id: Generated<number>;
  tipo: "falta_grave" | "falta_leve" | "suspension" | "tardanza";
  updated_at: string | null;
}

export interface FamiliasProfesionales {
  activo: Generated<number>;
  color: Generated<string>;
  created_at: string | null;
  descripcion: string | null;
  icono: Generated<string>;
  id: Generated<number>;
  nombre: string;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface FasesProyecto {
  completada: Generated<number>;
  created_at: string | null;
  descripcion: string | null;
  fecha_limite: string;
  id: Generated<number>;
  nombre: string;
  proyecto_id: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface FichasSalud {
  alergias: string | null;
  condiciones_medicas: string | null;
  contacto_emergencia: string | null;
  created_at: string | null;
  estudiante_id: number;
  id: Generated<number>;
  medicamentos: string | null;
  num_seguro: string | null;
  seguro_medico: string | null;
  telefono_emergencia: string | null;
  tenant_id: Generated<number>;
  tipo_sangre: string | null;
  updated_at: string | null;
}

export interface FotosAlbum {
  album_id: number;
  created_at: string | null;
  id: Generated<number>;
  orden: Generated<number>;
  ruta: string;
  tenant_id: Generated<number>;
  titulo: string | null;
  updated_at: string | null;
}

export interface FranjasHorarias {
  activa: Generated<number>;
  centro_id: number | null;
  created_at: string | null;
  es_recreo: Generated<number>;
  hora_fin: string;
  hora_inicio: string;
  id: Generated<number>;
  nombre: string | null;
  numero: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface Grados {
  activo: Generated<number>;
  ciclo: Generated<string>;
  created_at: string | null;
  id: Generated<number>;
  nivel: number;
  nombre: string;
  orden: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface Grupos {
  activo: Generated<number>;
  aula: string | null;
  capacidad: Generated<number>;
  created_at: string | null;
  deleted_at: string | null;
  grado_id: number;
  id: Generated<number>;
  school_year_id: number;
  seccion_id: number;
  tenant_id: Generated<number>;
  tutor_id: number | null;
  updated_at: string | null;
}

export interface HorarioDetalles {
  asignacion_id: number;
  aula_id: number | null;
  created_at: string | null;
  dia: "jueves" | "lunes" | "martes" | "miercoles" | "viernes";
  es_suplencia: Generated<number>;
  franja_id: number;
  horario_id: number;
  id: Generated<number>;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface Horarios {
  centro_id: number | null;
  conflictos: Json | null;
  creado_por: number | null;
  created_at: string | null;
  es_activo: Generated<number>;
  estado: Generated<"archivado" | "borrador" | "publicado">;
  generado_en: string | null;
  id: Generated<number>;
  iteraciones: number | null;
  nombre: Generated<string>;
  school_year_id: number;
  score: Decimal | null;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface ImportacionesCalificaciones {
  archivo_original: string;
  archivo_path: string;
  asignacion_id: number;
  completado_at: string | null;
  created_at: string | null;
  error_fatal: string | null;
  errores: Json | null;
  estado: Generated<"completado" | "fallido" | "pendiente" | "procesando">;
  id: Generated<number>;
  importados: Generated<number>;
  iniciado_at: string | null;
  omitidos: Generated<number>;
  periodo_id: number | null;
  tenant_id: number | null;
  total_filas: Generated<number>;
  updated_at: string | null;
  user_id: number;
}

export interface IncidentesMedicos {
  accion_tomada: string;
  created_at: string | null;
  descripcion: string;
  estudiante_id: number;
  fecha: string;
  hora: string | null;
  id: Generated<number>;
  notificado_representante: Generated<number>;
  remitido_a: string | null;
  tenant_id: Generated<number>;
  tipo: "accidente" | "alergia" | "enfermedad" | "otro";
  updated_at: string | null;
}

export interface IndicadoresAprendizaje {
  activo: Generated<number>;
  asignatura_id: number;
  created_at: string | null;
  descripcion: string;
  grado_id: number;
  id: Generated<number>;
  orden: Generated<number>;
  periodo_numero: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface IndicadoresLogro {
  activo: Generated<number>;
  codigo: string;
  competencia_id: number;
  created_at: string | null;
  descripcion: string;
  id: Generated<number>;
  orden: Generated<number>;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface Inscripciones {
  created_at: string | null;
  estado: Generated<"asignada" | "cancelada" | "pendiente">;
  estudiante_id: number;
  fecha_inscripcion: string;
  grado_id: number | null;
  grupo_id: number | null;
  id: Generated<number>;
  matricula_id: number | null;
  observaciones: string | null;
  origen: Generated<"continuidad" | "nueva" | "traslado">;
  school_year_id: number;
  tenant_id: number;
  updated_at: string | null;
}

export interface InscripcionesEvento {
  asistio: Generated<number>;
  created_at: string | null;
  estudiante_id: number;
  evento_id: number;
  fecha_inscripcion: string;
  id: Generated<number>;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface InsigniasEstudiante {
  created_at: string | null;
  fecha_obtencion: string;
  id: Generated<number>;
  matricula_id: number;
  tenant_id: Generated<number>;
  tipo: "asistencia_perfecta" | "cien_puntos" | "mejora_continua" | "quinientos_puntos" | "sin_faltas" | "top_estudiante";
  updated_at: string | null;
}

export interface InstrumentoCriterios {
  created_at: string | null;
  descripcion: string | null;
  id: Generated<number>;
  instrumento_id: number;
  nombre: string;
  orden: Generated<number>;
  peso_max: Generated<Decimal>;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface InstrumentoEvaluaciones {
  created_at: string | null;
  id: Generated<number>;
  instrumento_id: number;
  matricula_id: number;
  nivel_desempeno: string | null;
  observacion: string | null;
  ponderacion: Decimal | null;
  puntajes: Json | null;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface InstrumentosEvaluacion {
  asignacion_id: number | null;
  competencia: string | null;
  creado_por: number | null;
  created_at: string | null;
  deleted_at: string | null;
  descripcion: string | null;
  docente_id: number | null;
  fecha_aplicacion: string | null;
  id: Generated<number>;
  indicadores_logro: string | null;
  niveles_desempeno: Json | null;
  observaciones: string | null;
  periodo_id: number | null;
  publicado: Generated<number>;
  school_year_id: number;
  tenant_id: Generated<number>;
  tipo: Generated<"escala_estimacion" | "lista_cotejo" | "rubrica">;
  titulo: string;
  updated_at: string | null;
  valoracion_global: string | null;
}

export interface IntegrantesProyecto {
  created_at: string | null;
  estudiante_id: number;
  id: Generated<number>;
  proyecto_id: number;
  rol: Generated<"integrante" | "lider">;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface IntervencionesCaso {
  caso_id: number;
  created_at: string | null;
  descripcion: string;
  fecha: string;
  id: Generated<number>;
  resultado: string | null;
  siguiente_accion: string | null;
  tenant_id: Generated<number>;
  tipo_intervencion: Generated<"derivacion" | "llamada" | "otro" | "reunion" | "visita">;
  updated_at: string | null;
}

export interface Jobs {
  attempts: number;
  available_at: number;
  created_at: number;
  id: Generated<number>;
  payload: string;
  queue: string;
  reserved_at: number | null;
}

export interface Libros {
  autor: string;
  cantidad_disponible: Generated<number>;
  cantidad_total: Generated<number>;
  categoria: string;
  created_at: string | null;
  descripcion: string | null;
  id: Generated<number>;
  isbn: string | null;
  tenant_id: Generated<number>;
  titulo: string;
  updated_at: string | null;
}

export interface MallaCurricular {
  activo: Generated<number>;
  area: Generated<"academica" | "tecnica">;
  asignatura_id: number;
  created_at: string | null;
  es_obligatoria: Generated<number>;
  especialidad_id: number | null;
  grado_id: number;
  horas_anuales: number | null;
  horas_semanales: Generated<number>;
  id: Generated<number>;
  notas_curriculo: string | null;
  orden_display: Generated<number>;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface MaterialesClase {
  clase_virtual_id: number;
  competencia_id: number | null;
  contenido: string | null;
  created_at: string | null;
  fecha_limite: string | null;
  id: Generated<number>;
  limite_tiempo: number | null;
  orden: Generated<number>;
  periodo_id: number | null;
  permite_reentrega: Generated<number>;
  publicado: Generated<number>;
  publicar_en: string | null;
  puntos: number | null;
  subtipo: string | null;
  tenant_id: Generated<number>;
  tipo: "anuncio" | "evaluacion" | "material" | "tarea";
  titulo: string;
  updated_at: string | null;
  url_externo: string | null;
}

export interface Matriculas {
  created_at: string | null;
  estado: Generated<"activa" | "no_promovida" | "promovida" | "retirada" | "transferida">;
  estudiante_id: number;
  fecha_baja: string | null;
  fecha_matricula: string;
  grupo_id: number;
  id: Generated<number>;
  institucion_traslado: string | null;
  motivo_baja: string | null;
  numero_orden: number | null;
  observaciones: string | null;
  school_year_id: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface MensajeDestinatarios {
  archivado: Generated<number>;
  created_at: string | null;
  destinatario_id: number;
  eliminado: Generated<number>;
  id: Generated<number>;
  leido_at: string | null;
  mensaje_id: number;
  updated_at: string | null;
}

export interface Mensajes {
  adjunto_nombre: string | null;
  adjunto_path: string | null;
  archivado_destinatario: Generated<number>;
  archivado_remitente: Generated<number>;
  asunto: string;
  created_at: string | null;
  cuerpo: string;
  destinatario_id: number;
  id: Generated<number>;
  leido: Generated<number>;
  leido_en: string | null;
  mensaje_padre_id: number | null;
  remitente_id: number;
  tenant_id: Generated<number>;
  tipo: Generated<"circular" | "grupal" | "individual">;
  updated_at: string | null;
}

export interface Migrations {
  batch: number;
  id: Generated<number>;
  migration: string;
}

export interface ModelHasPermissions {
  model_id: number;
  model_type: string;
  permission_id: number;
}

export interface ModelHasRoles {
  model_id: number;
  model_type: string;
  role_id: number;
}

export interface Modules {
  activo: Generated<number>;
  categoria: Generated<"academico" | "administracion" | "bienestar" | "comunicacion" | "financiero" | "lms">;
  /**
   * Identificador usado en código: classroom, pagos, etc.
   */
  clave: string;
  created_at: string | null;
  descripcion: string | null;
  /**
   * Nombre de icono Bootstrap Icons
   */
  icono: string | null;
  id: Generated<number>;
  nombre: string;
  orden: Generated<number>;
  /**
   * Plan mínimo para acceder a este módulo
   */
  plan_minimo: Generated<"free" | "premium" | "pro">;
  updated_at: string | null;
}

export interface ModulosFormativos {
  activo: Generated<number>;
  codigo: string | null;
  created_at: string | null;
  creditos: Decimal | null;
  curso_tecnico_id: number;
  descripcion: string | null;
  duracion_horas: number | null;
  id: Generated<number>;
  nombre: string;
  orden: Generated<number>;
  tenant_id: number;
  updated_at: string | null;
}

export interface MovimientosInventario {
  articulo_id: number;
  cantidad: number;
  created_at: string | null;
  id: Generated<number>;
  motivo: string;
  tenant_id: Generated<number>;
  tipo: "ajuste" | "entrada" | "salida";
  updated_at: string | null;
  usuario_id: number;
}

export interface NominaEmpleados {
  activo: Generated<number>;
  banco: string | null;
  cargo: string;
  cedula: string | null;
  created_at: string | null;
  cuenta_bancaria: string | null;
  exento_isr: Generated<number>;
  fecha_ingreso: string;
  horas_semana: number | null;
  id: Generated<number>;
  notas: string | null;
  salario_base: Decimal;
  tenant_id: Generated<number>;
  tipo_contrato: Generated<"fijo" | "hora" | "temporal">;
  tss_porcentaje: Generated<Decimal>;
  updated_at: string | null;
  user_id: number;
}

export interface Notificaciones {
  created_at: string | null;
  datos: Json | null;
  id: Generated<number>;
  leida: Generated<number>;
  leida_en: string | null;
  mensaje: string;
  tenant_id: Generated<number>;
  tipo: string;
  titulo: string;
  updated_at: string | null;
  user_id: number;
}

export interface Observaciones {
  asignacion_id: number | null;
  created_at: string | null;
  docente_id: number;
  estudiante_id: number;
  id: Generated<number>;
  periodo_id: number | null;
  privada: Generated<number>;
  tenant_id: Generated<number>;
  texto: string;
  tipo: Generated<"academica" | "conductual" | "general" | "positiva">;
  updated_at: string | null;
}

export interface OpcionesPregunta {
  created_at: string | null;
  id: Generated<number>;
  orden: Generated<number>;
  pregunta_id: number;
  tenant_id: Generated<number>;
  texto: string;
  updated_at: string | null;
}

export interface PaginaSecciones {
  activo: Generated<number>;
  contenido: Json | null;
  created_at: string | null;
  id: Generated<number>;
  orden: Generated<number>;
  tenant_id: number;
  tipo: string;
  updated_at: string | null;
}

export interface Pagos {
  concepto: string;
  created_at: string | null;
  estado: Generated<"cancelado" | "pagado" | "pendiente" | "vencido">;
  fecha_pago: string | null;
  fecha_vencimiento: string;
  id: Generated<number>;
  matricula_id: number;
  metodo_pago: string | null;
  monto: Decimal;
  notas: string | null;
  numero_comprobante_fiscal: string | null;
  referencia: string | null;
  registrado_por: number | null;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface PagosNomina {
  bonificacion: Generated<Decimal>;
  created_at: string | null;
  deducciones: Generated<Decimal>;
  desc_isr: Generated<Decimal>;
  desc_otros: Generated<Decimal>;
  desc_tss: Generated<Decimal>;
  fecha_pago: string | null;
  horas_extra: Generated<Decimal>;
  id: Generated<number>;
  mes: string;
  metodo_pago: string | null;
  nomina_empleado_id: number;
  notas_deducciones: string | null;
  otros_ingresos: Generated<Decimal>;
  pagado: Generated<number>;
  pagado_por: number | null;
  referencia_pago: string | null;
  salario_bruto: Decimal;
  salario_neto: Decimal;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface ParadasRuta {
  created_at: string | null;
  hora_estimada: string | null;
  id: Generated<number>;
  nombre: string;
  orden: Generated<number>;
  ruta_id: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface PasswordResetTokens {
  created_at: string | null;
  email: string;
  token: string;
}

export interface Periodos {
  activo: Generated<number>;
  cerrado: Generated<number>;
  created_at: string | null;
  fecha_fin: string;
  fecha_inicio: string;
  id: Generated<number>;
  nombre: string;
  numero: number;
  school_year_id: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface Permissions {
  created_at: string | null;
  guard_name: string;
  id: Generated<number>;
  name: string;
  updated_at: string | null;
}

export interface PersonalAccessTokens {
  abilities: string | null;
  created_at: string | null;
  expires_at: string | null;
  id: Generated<number>;
  last_used_at: string | null;
  name: string;
  token: string;
  tokenable_id: number;
  tokenable_type: string;
  updated_at: string | null;
}

export interface PlanClaseMomentos {
  actividades: string | null;
  area_curricular: string | null;
  competencias_especificas: string | null;
  contenidos: string | null;
  created_at: string | null;
  duracion_minutos: number | null;
  id: Generated<number>;
  indicador_logro: string | null;
  orden: Generated<number>;
  plan_clase_id: number;
  recursos: string | null;
  tenant_id: Generated<number>;
  tipo: "cierre" | "desarrollo" | "inicio";
  updated_at: string | null;
}

export interface PlanesClase {
  archivo_nombre: string | null;
  archivo_path: string | null;
  archivo_tipo: string | null;
  area: Generated<"academica" | "tecnica">;
  asignacion_id: number | null;
  creado_por: number | null;
  created_at: string | null;
  deleted_at: string | null;
  docente_id: number | null;
  estrategias: Json | null;
  fecha_fin: string | null;
  fecha_inicio: string | null;
  grado_seccion: string | null;
  id: Generated<number>;
  intencion_pedagogica: string | null;
  observacion: string | null;
  planif_unidad_id: number | null;
  planificacion_id: number | null;
  publicado: Generated<number>;
  school_year_id: number;
  semana: string | null;
  tenant_id: Generated<number>;
  tipo_plan: Generated<"diaria" | "mensual" | "quincenal" | "semanal">;
  titulo: string;
  updated_at: string | null;
}

export interface PlanEvaluacionPeriodos {
  asignacion_id: number;
  created_at: string | null;
  examen: Generated<number>;
  id: Generated<number>;
  observaciones: string | null;
  participacion: Generated<number>;
  periodo_id: number;
  practicas: Generated<number>;
  proyecto: Generated<number>;
  publicado: Generated<number>;
  tareas: Generated<number>;
  tenant_id: number;
  updated_at: string | null;
}

export interface PlanifAnuales {
  asignacion_id: number;
  created_at: string | null;
  descripcion: string | null;
  docente_id: number;
  id: Generated<number>;
  school_year_id: number | null;
  tenant_id: number;
  titulo: string;
  updated_at: string | null;
}

export interface PlanificacionActividades {
  act_cierre: string | null;
  act_desarrollo: string | null;
  act_inicio: string | null;
  actividad_numero: number | null;
  created_at: string | null;
  estrategias: string | null;
  id: Generated<number>;
  instrumentos_evaluacion: string | null;
  objetivo: string | null;
  planificacion_id: number;
  ra_codigo: string | null;
  ra_descripcion: string | null;
  recursos: string | null;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface Planificaciones {
  asignacion_id: number;
  creado_por: number | null;
  created_at: string | null;
  denominacion: string | null;
  familia_profesional: string | null;
  fecha_fin: string | null;
  fecha_inicio: string | null;
  horas: Decimal | null;
  id: Generated<number>;
  mf_codigo: string | null;
  modulo_nombre: string | null;
  nivel: string | null;
  publicado: Generated<number>;
  school_year_id: number;
  sesion: string | null;
  tenant_id: Generated<number>;
  tipo: Generated<"actividad" | "ra">;
  uc_codigo: string | null;
  updated_at: string | null;
}

export interface PlanificacionRaItems {
  actividades: string | null;
  contenidos: string | null;
  created_at: string | null;
  elementos_capacidad: Json | null;
  fechas: Json | null;
  id: Generated<number>;
  instrumentos_evaluacion: string | null;
  nivel_taxonomico: string | null;
  orden: Generated<number>;
  planificacion_id: number;
  ra_codigo: string | null;
  ra_descripcion: string | null;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface PlanifUnidades {
  competencias: Json | null;
  contenidos: string | null;
  created_at: string | null;
  estrategias: string | null;
  evaluacion: string | null;
  fecha_fin: string | null;
  fecha_inicio: string | null;
  id: Generated<number>;
  indicadores: string | null;
  numero: Generated<number>;
  objetivos: string | null;
  periodo: string | null;
  planif_anual_id: number;
  recursos: string | null;
  semanas: number | null;
  tenant_id: number;
  titulo: string;
  updated_at: string | null;
}

export interface Plans {
  activo: Generated<number>;
  almacenamiento_gb: Generated<number>;
  /**
   * Array de bullets para la landing
   */
  caracteristicas: Json | null;
  created_at: string | null;
  descripcion: string | null;
  es_popular: Generated<number>;
  id: Generated<number>;
  limite_docentes: Generated<number>;
  limite_estudiantes: Generated<number>;
  limite_usuarios: Generated<number>;
  moneda: Generated<string>;
  nombre: string;
  orden: Generated<number>;
  /**
   * Precio anual con descuento
   */
  precio_anual: Generated<Decimal>;
  precio_mensual: Generated<Decimal>;
  /**
   * free | pro | premium
   */
  slug: string;
  updated_at: string | null;
}

export interface PlantillasComunicacion {
  activa: Generated<number>;
  asunto: string | null;
  canal: string;
  created_at: string | null;
  cuerpo: string | null;
  evento: string;
  id: Generated<number>;
  tenant_id: number;
  updated_at: string | null;
}

export interface PreguntasEncuesta {
  created_at: string | null;
  encuesta_id: number;
  id: Generated<number>;
  orden: Generated<number>;
  tenant_id: Generated<number>;
  texto: string;
  tipo: Generated<"escala_1_5" | "opcion_multiple" | "texto_libre">;
  updated_at: string | null;
}

export interface PreMatriculas {
  apellidos: string;
  cedula_estudiante: string | null;
  cedula_representante: string;
  codigo: string | null;
  created_at: string | null;
  direccion: string;
  documentos: Json | null;
  email: string;
  estado: Generated<"aprobada" | "pendiente" | "rechazada">;
  estudiante_id: number | null;
  fecha_nacimiento: string;
  genero: string | null;
  grado_solicitado: string;
  id: Generated<number>;
  lugar_nacimiento: string | null;
  nombre_representante: string;
  nombres: string;
  notas_admin: string | null;
  relacion_representante: string | null;
  telefono: string;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface PrestamosBiblioteca {
  created_at: string | null;
  estado: Generated<"activo" | "devuelto" | "vencido">;
  estudiante_id: number;
  fecha_devolucion: string | null;
  fecha_prestamo: string;
  fecha_vencimiento: string;
  id: Generated<number>;
  libro_id: number;
  notas: string | null;
  renovaciones: Generated<number>;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface PrestamosEquipo {
  created_at: string | null;
  equipo_id: number;
  estado: Generated<"activo" | "devuelto" | "vencido">;
  fecha_devolucion: string | null;
  fecha_prestamo: string;
  fecha_vencimiento: string;
  id: Generated<number>;
  motivo: string | null;
  tenant_id: Generated<number>;
  updated_at: string | null;
  usuario_id: number;
}

export interface ProductosCafeteria {
  activo: Generated<number>;
  categoria: Generated<"bebida" | "comida" | "otro" | "snack">;
  created_at: string | null;
  id: Generated<number>;
  nombre: string;
  precio: Decimal;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface PromediosPeriodo {
  asignacion_id: number;
  calculado_en: string | null;
  created_at: string | null;
  id: Generated<number>;
  indicador: "Bueno" | "En proceso" | "Excelente" | "Insuficiente" | null;
  matricula_id: number;
  pct_asistencia: Decimal | null;
  periodo_id: number;
  promedio: Decimal | null;
  publicado: Generated<number>;
  school_year_id: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
  valor_cualitativo: number | null;
}

export interface Promociones {
  created_at: string | null;
  decidido_por: number | null;
  estado: Generated<"condicionado" | "no_promovido" | "pendiente" | "promovido">;
  fecha_decision: string | null;
  id: Generated<number>;
  materias_reprobadas: Generated<number>;
  materias_reprobadas_detalle: Json | null;
  matricula_id: number;
  observacion: string | null;
  pct_asistencia: Decimal | null;
  promedio_final: Decimal | null;
  school_year_id: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface ProyectosEscolares {
  area: Generated<"arte" | "ciencias" | "humanidades" | "matematica" | "otro" | "tecnologia">;
  created_at: string | null;
  descripcion: string | null;
  estado: Generated<"desarrollo" | "finalizado" | "planificacion" | "presentado">;
  fecha_fin: string | null;
  fecha_inicio: string;
  id: Generated<number>;
  school_year_id: number;
  tenant_id: Generated<number>;
  titulo: string;
  tutor_id: number;
  updated_at: string | null;
}

export interface Publicaciones {
  contenido: string;
  creado_por: number | null;
  created_at: string | null;
  estado: Generated<"borrador" | "publicado">;
  fecha: string;
  id: Generated<number>;
  imagen_alineacion: Generated<string>;
  imagen_destacada: string | null;
  tenant_id: number;
  tipo: Generated<"actividad" | "aviso" | "comunicado" | "convocatoria" | "logro" | "noticia">;
  titulo: string;
  updated_at: string | null;
  visible: Generated<number>;
}

export interface PuntosEstudiante {
  categoria: Generated<"academico" | "asistencia" | "conducta" | "extra" | "participacion">;
  concepto: string;
  created_at: string | null;
  fecha: string;
  id: Generated<number>;
  matricula_id: number;
  puntos: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface QrAsistenciaTokens {
  activo: Generated<number>;
  asignacion_id: number;
  created_at: string | null;
  docente_id: number;
  duracion_minutos: Generated<number>;
  expires_at: string;
  fecha: string;
  id: Generated<number>;
  tenant_id: number | null;
  token: string;
  updated_at: string | null;
}

export interface Reconocimientos {
  created_at: string | null;
  descripcion: string | null;
  emitido_por_id: number;
  entregado: Generated<number>;
  estudiante_id: number;
  fecha: string;
  fecha_entrega: string | null;
  id: Generated<number>;
  tenant_id: Generated<number>;
  tipo_id: number;
  titulo: string;
  updated_at: string | null;
}

export interface RecursosFisicos {
  activo: Generated<number>;
  capacidad: number | null;
  created_at: string | null;
  descripcion: string | null;
  id: Generated<number>;
  nombre: string;
  tenant_id: Generated<number>;
  tipo: Generated<"auditorio" | "aula" | "cancha" | "laboratorio" | "otro" | "proyector" | "sala_computadoras">;
  ubicacion: string | null;
  updated_at: string | null;
}

export interface RecursosMateria {
  archivo_nombre: string | null;
  archivo_path: string | null;
  asignacion_id: number;
  created_at: string | null;
  created_by: number;
  descripcion: string | null;
  id: Generated<number>;
  orden: Generated<number>;
  publicado: Generated<number>;
  school_year_id: number | null;
  tenant_id: Generated<number>;
  tipo: Generated<"documento" | "enlace" | "imagen" | "otro" | "video">;
  titulo: string;
  updated_at: string | null;
  url: string | null;
}

export interface RendimientoCache {
  calculado_en: string;
  grupo_id: number;
  id: Generated<number>;
  pct_bajo: Generated<Decimal>;
  pct_bueno: Generated<Decimal>;
  pct_excelente: Generated<Decimal>;
  pct_regular: Generated<Decimal>;
  periodo_id: number | null;
  promedio_grupo: Decimal | null;
  school_year_id: number;
  tenant_id: Generated<number>;
  total_aprobados: Generated<number>;
  total_estudiantes: Generated<number>;
  total_reprobados: Generated<number>;
  total_riesgo: Generated<number>;
}

export interface Representantes {
  apellidos: string;
  cedula: string | null;
  created_at: string | null;
  direccion: string | null;
  email: string | null;
  foto: string | null;
  id: Generated<number>;
  nombres: string;
  ocupacion: string | null;
  telefono: string | null;
  telefono_trabajo: string | null;
  tenant_id: Generated<number>;
  updated_at: string | null;
  user_id: number;
}

export interface ReservasRecurso {
  created_at: string | null;
  estado: Generated<"aprobada" | "pendiente" | "rechazada">;
  fecha: string;
  hora_fin: string;
  hora_inicio: string;
  id: Generated<number>;
  motivo: string;
  notas: string | null;
  recurso_id: number;
  solicitante_id: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface RespuestasEncuesta {
  created_at: string | null;
  encuesta_id: number;
  escala_valor: number | null;
  id: Generated<number>;
  opcion_id: number | null;
  pregunta_id: number;
  respuesta_texto: string | null;
  tenant_id: Generated<number>;
  updated_at: string | null;
  user_id: number;
}

export interface RespuestasTicket {
  created_at: string | null;
  id: Generated<number>;
  mensaje: string;
  tenant_id: Generated<number>;
  ticket_id: number;
  updated_at: string | null;
  user_id: number;
}

export interface RestriccionesHorario {
  centro_id: number | null;
  clave: string;
  created_at: string | null;
  descripcion: string | null;
  id: Generated<number>;
  school_year_id: number | null;
  tenant_id: Generated<number>;
  updated_at: string | null;
  valor: string;
}

export interface ResultadosAprendizaje {
  activo: Generated<number>;
  asignatura_id: number;
  created_at: string | null;
  descripcion: string;
  id: Generated<number>;
  numero: number;
  peso: Decimal | null;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface Reuniones {
  agenda: string | null;
  convocante_id: number | null;
  created_at: string | null;
  estado: Generated<"cancelada" | "programada" | "realizada">;
  fecha: string;
  id: Generated<number>;
  lugar: string | null;
  participantes: string | null;
  tenant_id: Generated<number>;
  tipo: Generated<"comite" | "consejo_directivo" | "otra" | "reunion_docentes" | "reunion_padres">;
  titulo: string;
  updated_at: string | null;
}

export interface RoleHasPermissions {
  permission_id: number;
  role_id: number;
}

export interface Roles {
  created_at: string | null;
  guard_name: string;
  id: Generated<number>;
  name: string;
  updated_at: string | null;
}

export interface RubricaAplicaciones {
  aplicado_en: string | null;
  asignacion_id: number;
  created_at: string | null;
  id: Generated<number>;
  matricula_id: number;
  observaciones: string | null;
  puntaje: Generated<Decimal>;
  puntaje_max: Generated<Decimal>;
  resultados: Json | null;
  rubrica_id: number;
  tenant_id: number;
  updated_at: string | null;
}

export interface Rubricas {
  asignatura_id: number | null;
  created_at: string | null;
  criterios: Json;
  descripcion: string | null;
  docente_id: number;
  id: Generated<number>;
  niveles: Json;
  tenant_id: number;
  titulo: string;
  updated_at: string | null;
}

export interface RutasTransporte {
  activo: Generated<number>;
  capacidad: Generated<number>;
  conductor: string | null;
  created_at: string | null;
  descripcion: string | null;
  horario_regreso: string | null;
  horario_salida: string | null;
  id: Generated<number>;
  nombre: string;
  telefono_conductor: string | null;
  tenant_id: Generated<number>;
  updated_at: string | null;
  vehiculo: string | null;
}

export interface SchoolYears {
  activo: Generated<number>;
  created_at: string | null;
  fecha_fin: string;
  fecha_inicio: string;
  id: Generated<number>;
  nombre: string;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface Secciones {
  created_at: string | null;
  id: Generated<number>;
  nombre: string;
  orden: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface SesionesTutoria {
  acuerdos: string | null;
  created_at: string | null;
  descripcion: string | null;
  estudiantes_atendidos: string | null;
  fecha: string;
  id: Generated<number>;
  proxima_sesion: string | null;
  tema: string;
  tenant_id: Generated<number>;
  tutoria_id: number;
  updated_at: string | null;
}

export interface Sessions {
  id: string;
  ip_address: string | null;
  last_activity: number;
  payload: string;
  user_agent: string | null;
  user_id: number | null;
}

export interface SigerdConfig {
  activo: Generated<number>;
  anio_sigerd: string | null;
  codigo_centro: string;
  created_at: string | null;
  distrito: string | null;
  id: Generated<number>;
  modalidad: Generated<string>;
  nombre_centro: string | null;
  regional: string | null;
  sector: Generated<string>;
  tenant_id: number;
  updated_at: string | null;
}

export interface SigerdExportLogs {
  archivo_nombre: string | null;
  created_at: string | null;
  errores_validacion: Json | null;
  formato: string;
  grupo_id: number | null;
  id: Generated<number>;
  notas: string | null;
  periodo_id: number | null;
  school_year_id: number;
  tenant_id: number;
  tipo: string;
  total_registros: Generated<number>;
  user_id: number;
}

export interface SolicitudesDocente {
  adjunto: string | null;
  asunto: string;
  created_at: string | null;
  descripcion: string;
  docente_id: number;
  estado: Generated<"aprobada" | "en_proceso" | "pendiente" | "rechazada">;
  fecha_fin: string | null;
  fecha_inicio: string | null;
  id: Generated<number>;
  respondido_en: string | null;
  respondido_por: number | null;
  respuesta: string | null;
  tenant_id: number | null;
  tipo: string;
  updated_at: string | null;
}

export interface SolicitudesEstudiante {
  adjunto: string | null;
  asunto: string;
  created_at: string | null;
  descripcion: string;
  estado: Generated<"aprobada" | "en_proceso" | "pendiente" | "rechazada">;
  estudiante_id: number;
  fecha_evento: string | null;
  id: Generated<number>;
  respondido_en: string | null;
  respondido_por: number | null;
  respuesta: string | null;
  tenant_id: number | null;
  tipo: string;
  updated_at: string | null;
}

export interface SolicitudesRepresentante {
  adjunto: string | null;
  asunto: string;
  created_at: string | null;
  descripcion: string;
  docente_id: number | null;
  estado: Generated<"aprobada" | "en_proceso" | "pendiente" | "rechazada">;
  estudiante_id: number | null;
  fecha_evento: string | null;
  id: Generated<number>;
  representante_id: number;
  respondido_en: string | null;
  respondido_por: number | null;
  respuesta: string | null;
  tenant_id: number | null;
  tipo: string;
  updated_at: string | null;
}

export interface StripeWebhookEvents {
  created_at: string | null;
  error: string | null;
  id: Generated<number>;
  status: Generated<string>;
  stripe_event_id: string;
  type: string;
  updated_at: string | null;
}

export interface Subscriptions {
  ciclo: Generated<"anual" | "mensual">;
  created_at: string | null;
  estado: Generated<"activa" | "cancelada" | "pendiente" | "prueba" | "suspendida" | "vencida">;
  fecha_fin: string;
  fecha_inicio: string;
  id: Generated<number>;
  metadatos: Json | null;
  /**
   * stripe|paypal|transferencia|efectivo
   */
  metodo_pago: string | null;
  moneda: Generated<string>;
  monto_pagado: Decimal | null;
  plan_id: number;
  referencia_pago: string | null;
  stripe_payment_intent: string | null;
  stripe_session_id: string | null;
  tenant_id: number;
  updated_at: string | null;
}

export interface Suplencias {
  created_at: string | null;
  docente_original_id: number;
  docente_suplente_id: number | null;
  estado: Generated<"cubierta" | "pendiente" | "sin_cubrir">;
  fecha: string;
  horario_detalle_id: number;
  id: Generated<number>;
  motivo: string | null;
  notas_suplente: string | null;
  registrado_por: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface SupportMessages {
  created_at: string | null;
  id: Generated<number>;
  leido: Generated<number>;
  mensaje: string;
  origen: Generated<"admin" | "visitor">;
  session_id: number;
  updated_at: string | null;
  user_id: number | null;
}

export interface SupportSessions {
  atendido_por: number | null;
  created_at: string | null;
  id: Generated<number>;
  status: Generated<"closed" | "open" | "resolved">;
  tenant_id: number;
  token: string;
  ultimo_mensaje_at: string | null;
  updated_at: string | null;
  visitor_email: string | null;
  visitor_nombre: string;
  visitor_telefono: string | null;
}

export interface SystemSettings {
  created_at: string | null;
  id: Generated<number>;
  key: string;
  tenant_id: Generated<number>;
  updated_at: string | null;
  value: string | null;
}

export interface Tareas {
  activo: Generated<number>;
  asignacion_id: number;
  created_at: string | null;
  descripcion: string | null;
  fecha_limite: string;
  id: Generated<number>;
  puntos_valor: number | null;
  tenant_id: Generated<number>;
  tipo: Generated<"actividad" | "evaluacion" | "proyecto" | "tarea">;
  titulo: string;
  updated_at: string | null;
}

export interface TenantChatMessages {
  archivo_nombre: string | null;
  archivo_url: string | null;
  created_at: string | null;
  id: Generated<number>;
  leido_por_todos: Generated<number>;
  mensaje: string;
  tenant_id: number;
  tipo: Generated<string>;
  updated_at: string | null;
  user_id: number;
}

export interface TenantFeatures {
  activo: Generated<number>;
  /**
   * Configuración específica del módulo
   */
  config: Json | null;
  created_at: string | null;
  /**
   * Nombre del módulo/característica
   */
  feature: string;
  id: Generated<number>;
  tenant_id: number;
  updated_at: string | null;
}

export interface TenantModules {
  activo: Generated<number>;
  /**
   * Configuración específica del módulo para este tenant
   */
  config: Json | null;
  created_at: string | null;
  id: Generated<number>;
  module_id: number;
  tenant_id: number;
  updated_at: string | null;
}

export interface Tenants {
  ciudad: string | null;
  color_primario: Generated<string>;
  color_secundario: Generated<string>;
  created_at: string | null;
  deleted_at: string | null;
  direccion: string | null;
  /**
   * Subdominio: colegio1 → colegio1.zuraedu.com
   */
  dominio: string;
  /**
   * Dominio propio: miescuela.edu.do
   */
  dominio_personalizado: string | null;
  email_contacto: string | null;
  estado: Generated<"activo" | "cancelado" | "prueba" | "suspendido">;
  fecha_registro: string | null;
  fecha_vencimiento: string | null;
  id: Generated<number>;
  is_demo_temporal: Generated<number>;
  logo: string | null;
  max_docentes: Generated<number>;
  max_estudiantes: Generated<number>;
  max_usuarios: Generated<number>;
  metadatos: Json | null;
  nombre_institucion: string;
  onboarding_completado: Generated<number>;
  onboarding_paso: Generated<number>;
  pais: Generated<string>;
  plan: Generated<"basico" | "free" | "pro">;
  plan_id: number | null;
  stripe_customer_id: string | null;
  telefono_contacto: string | null;
  tipo: Generated<"instituto" | "privado" | "publico" | "tecnico">;
  updated_at: string | null;
}

export interface TicketsSoporte {
  asignado_a_id: number | null;
  categoria: Generated<"academico" | "administrativo" | "otro" | "tecnico">;
  causa_raiz: string | null;
  created_at: string | null;
  descripcion: string;
  estado: Generated<"abierto" | "cerrado" | "en_proceso" | "resuelto">;
  id: Generated<number>;
  prioridad: Generated<"alta" | "baja" | "media" | "urgente">;
  sla_incumplido: Generated<number>;
  sla_vencimiento_at: string | null;
  solicitante_id: number;
  tenant_id: Generated<number>;
  titulo: string;
  updated_at: string | null;
}

export interface TiposReconocimiento {
  /**
   * Clase Tailwind p.ej. bg-yellow-400
   */
  color: string | null;
  created_at: string | null;
  descripcion: string | null;
  /**
   * Nombre icono HeroIcons / emoji
   */
  icono: string | null;
  id: Generated<number>;
  nombre: string;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface Tutorias {
  activo: Generated<number>;
  created_at: string | null;
  descripcion: string | null;
  docente_id: number;
  grupo_id: number;
  id: Generated<number>;
  school_year_id: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface Users {
  activo: Generated<number>;
  apellidos: string | null;
  area_trabajo: string | null;
  cedula: string | null;
  created_at: string | null;
  email: string;
  email_verified_at: string | null;
  id: Generated<number>;
  motivo_rechazo: string | null;
  must_change_password: Generated<number>;
  name: string;
  notif_push_prefs: Json | null;
  password: string;
  pendiente_aprobacion: Generated<number>;
  profile_photo: string | null;
  remember_token: string | null;
  telefono: string | null;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface VentasCafeteria {
  created_at: string | null;
  created_by_id: number | null;
  descripcion: string | null;
  estudiante_id: number;
  id: Generated<number>;
  monto: Decimal;
  producto_id: number | null;
  saldo_anterior: Generated<Decimal>;
  saldo_nuevo: Generated<Decimal>;
  tenant_id: Generated<number>;
  tipo: Generated<"ajuste" | "recarga" | "venta">;
  updated_at: string | null;
}

export interface ZcIntentos {
  created_at: string | null;
  estado: Generated<"abandonado" | "en_curso" | "finalizado">;
  finalizado_en: string | null;
  id: Generated<number>;
  iniciado_en: string;
  matricula_id: number;
  numero_intento: Generated<number>;
  puntuacion: Decimal | null;
  puntuacion_max: Decimal | null;
  quiz_id: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface ZcOpciones {
  created_at: string | null;
  es_correcta: Generated<number>;
  id: Generated<number>;
  orden: Generated<number>;
  pregunta_id: number;
  tenant_id: Generated<number>;
  texto: string;
  updated_at: string | null;
}

export interface ZcPreguntas {
  created_at: string | null;
  enunciado: string;
  id: Generated<number>;
  imagen: string | null;
  orden: Generated<number>;
  puntos: Generated<Decimal>;
  quiz_id: number;
  tenant_id: Generated<number>;
  tipo: "abierta" | "multiple" | "verdadero_falso";
  updated_at: string | null;
}

export interface ZcQuizzes {
  aleatorizar_preguntas: Generated<number>;
  autocorreccion: Generated<number>;
  created_at: string | null;
  duracion_minutos: number | null;
  id: Generated<number>;
  intentos_max: Generated<number>;
  material_id: number;
  mostrar_respuestas: Generated<number>;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface ZcRecursos {
  clase_virtual_id: number;
  creado_por: number;
  created_at: string | null;
  descripcion: string | null;
  id: Generated<number>;
  nombre_archivo: string | null;
  orden: Generated<number>;
  publico: Generated<number>;
  ruta_archivo: string | null;
  tenant_id: Generated<number>;
  tipo: "enlace" | "imagen" | "otro" | "pdf" | "presentacion" | "video";
  titulo: string;
  updated_at: string | null;
  url: string | null;
}

export interface ZcRespuestas {
  created_at: string | null;
  es_correcta: number | null;
  id: Generated<number>;
  intento_id: number;
  opcion_id: number | null;
  pregunta_id: number;
  puntos_obtenidos: Decimal | null;
  tenant_id: Generated<number>;
  texto_respuesta: string | null;
  updated_at: string | null;
}

export interface ZcRubricCalificaciones {
  comentario: string | null;
  created_at: string | null;
  criterio_id: number;
  entrega_id: number;
  id: Generated<number>;
  puntaje: Generated<Decimal>;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface ZcRubricCriterios {
  created_at: string | null;
  descripcion: string | null;
  id: Generated<number>;
  nombre: string;
  orden: Generated<number>;
  puntaje_max: Generated<Decimal>;
  rubric_id: number;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface ZcRubrics {
  created_at: string | null;
  descripcion: string | null;
  id: Generated<number>;
  material_id: number;
  nombre: string;
  tenant_id: Generated<number>;
  updated_at: string | null;
}

export interface DB {
  academic_risk_scores: AcademicRiskScores;
  activity_logs: ActivityLogs;
  acuerdos_reunion: AcuerdosReunion;
  albumes: Albumes;
  alertas_sistema: AlertasSistema;
  archivos_entrega: ArchivosEntrega;
  archivos_material: ArchivosMaterial;
  areas: Areas;
  areas_tecnicas: AreasTecnicas;
  articulos_inventario: ArticulosInventario;
  asignaciones: Asignaciones;
  asignaturas: Asignaturas;
  asistencias: Asistencias;
  aulas: Aulas;
  avisos_emergencia: AvisosEmergencia;
  backup_runs: BackupRuns;
  banco_preguntas: BancoPreguntas;
  becas: Becas;
  becas_estudiante: BecasEstudiante;
  boletin_observaciones: BoletinObservaciones;
  boletines_config: BoletinesConfig;
  cache: Cache;
  cache_locks: CacheLocks;
  calendario_academico: CalendarioAcademico;
  calendario_destinatarios: CalendarioDestinatarios;
  calificacion_audits: CalificacionAudits;
  calificaciones: Calificaciones;
  calificaciones_academicas: CalificacionesAcademicas;
  capacitaciones_vistas: CapacitacionesVistas;
  carnet_accesos: CarnetAccesos;
  carnet_identidades: CarnetIdentidades;
  carnet_zonas: CarnetZonas;
  casos_seguimiento: CasosSeguimiento;
  clases_virtuales: ClasesVirtuales;
  classroom_messages: ClassroomMessages;
  comentarios_classroom: ComentariosClassroom;
  competencias_especificas: CompetenciasEspecificas;
  comunicado_lecturas: ComunicadoLecturas;
  comunicados: Comunicados;
  concepto_pagos: ConceptoPagos;
  conducta_registros: ConductaRegistros;
  config_calificaciones: ConfigCalificaciones;
  config_institucional: ConfigInstitucional;
  cursos_tecnicos: CursosTecnicos;
  device_tokens: DeviceTokens;
  diario_clases: DiarioClases;
  disponibilidad_docente: DisponibilidadDocente;
  docente_especialidad: DocenteEspecialidad;
  docentes: Docentes;
  encuestas: Encuestas;
  encuestas_interes: EncuestasInteres;
  entregas_classroom: EntregasClassroom;
  entregas_tarea: EntregasTarea;
  equipos: Equipos;
  especialidades_tecnicas: EspecialidadesTecnicas;
  estudiante_representante: EstudianteRepresentante;
  estudiantes: Estudiantes;
  estudiantes_ruta: EstudiantesRuta;
  eva_intentos: EvaIntentos;
  eva_preguntas: EvaPreguntas;
  eva_quizzes: EvaQuizzes;
  evaluaciones_docentes: EvaluacionesDocentes;
  evaluaciones_indicadores: EvaluacionesIndicadores;
  evaluaciones_registro: EvaluacionesRegistro;
  eventos: Eventos;
  failed_jobs: FailedJobs;
  faltas_disciplinarias: FaltasDisciplinarias;
  familias_profesionales: FamiliasProfesionales;
  fases_proyecto: FasesProyecto;
  fichas_salud: FichasSalud;
  fotos_album: FotosAlbum;
  franjas_horarias: FranjasHorarias;
  grados: Grados;
  grupos: Grupos;
  horario_detalles: HorarioDetalles;
  horarios: Horarios;
  importaciones_calificaciones: ImportacionesCalificaciones;
  incidentes_medicos: IncidentesMedicos;
  indicadores_aprendizaje: IndicadoresAprendizaje;
  indicadores_logro: IndicadoresLogro;
  inscripciones: Inscripciones;
  inscripciones_evento: InscripcionesEvento;
  insignias_estudiante: InsigniasEstudiante;
  instrumento_criterios: InstrumentoCriterios;
  instrumento_evaluaciones: InstrumentoEvaluaciones;
  instrumentos_evaluacion: InstrumentosEvaluacion;
  integrantes_proyecto: IntegrantesProyecto;
  intervenciones_caso: IntervencionesCaso;
  jobs: Jobs;
  libros: Libros;
  malla_curricular: MallaCurricular;
  materiales_clase: MaterialesClase;
  matriculas: Matriculas;
  mensaje_destinatarios: MensajeDestinatarios;
  mensajes: Mensajes;
  migrations: Migrations;
  model_has_permissions: ModelHasPermissions;
  model_has_roles: ModelHasRoles;
  modules: Modules;
  modulos_formativos: ModulosFormativos;
  movimientos_inventario: MovimientosInventario;
  nomina_empleados: NominaEmpleados;
  notificaciones: Notificaciones;
  observaciones: Observaciones;
  opciones_pregunta: OpcionesPregunta;
  pagina_secciones: PaginaSecciones;
  pagos: Pagos;
  pagos_nomina: PagosNomina;
  paradas_ruta: ParadasRuta;
  password_reset_tokens: PasswordResetTokens;
  periodos: Periodos;
  permissions: Permissions;
  personal_access_tokens: PersonalAccessTokens;
  plan_clase_momentos: PlanClaseMomentos;
  plan_evaluacion_periodos: PlanEvaluacionPeriodos;
  planes_clase: PlanesClase;
  planif_anuales: PlanifAnuales;
  planif_unidades: PlanifUnidades;
  planificacion_actividades: PlanificacionActividades;
  planificacion_ra_items: PlanificacionRaItems;
  planificaciones: Planificaciones;
  plans: Plans;
  plantillas_comunicacion: PlantillasComunicacion;
  pre_matriculas: PreMatriculas;
  preguntas_encuesta: PreguntasEncuesta;
  prestamos_biblioteca: PrestamosBiblioteca;
  prestamos_equipo: PrestamosEquipo;
  productos_cafeteria: ProductosCafeteria;
  promedios_periodo: PromediosPeriodo;
  promociones: Promociones;
  proyectos_escolares: ProyectosEscolares;
  publicaciones: Publicaciones;
  puntos_estudiante: PuntosEstudiante;
  qr_asistencia_tokens: QrAsistenciaTokens;
  reconocimientos: Reconocimientos;
  recursos_fisicos: RecursosFisicos;
  recursos_materia: RecursosMateria;
  rendimiento_cache: RendimientoCache;
  representantes: Representantes;
  reservas_recurso: ReservasRecurso;
  respuestas_encuesta: RespuestasEncuesta;
  respuestas_ticket: RespuestasTicket;
  restricciones_horario: RestriccionesHorario;
  resultados_aprendizaje: ResultadosAprendizaje;
  reuniones: Reuniones;
  role_has_permissions: RoleHasPermissions;
  roles: Roles;
  rubrica_aplicaciones: RubricaAplicaciones;
  rubricas: Rubricas;
  rutas_transporte: RutasTransporte;
  school_years: SchoolYears;
  secciones: Secciones;
  sesiones_tutoria: SesionesTutoria;
  sessions: Sessions;
  sigerd_config: SigerdConfig;
  sigerd_export_logs: SigerdExportLogs;
  solicitudes_docente: SolicitudesDocente;
  solicitudes_estudiante: SolicitudesEstudiante;
  solicitudes_representante: SolicitudesRepresentante;
  stripe_webhook_events: StripeWebhookEvents;
  subscriptions: Subscriptions;
  suplencias: Suplencias;
  support_messages: SupportMessages;
  support_sessions: SupportSessions;
  system_settings: SystemSettings;
  tareas: Tareas;
  tenant_chat_messages: TenantChatMessages;
  tenant_features: TenantFeatures;
  tenant_modules: TenantModules;
  tenants: Tenants;
  tickets_soporte: TicketsSoporte;
  tipos_reconocimiento: TiposReconocimiento;
  tutorias: Tutorias;
  users: Users;
  ventas_cafeteria: VentasCafeteria;
  zc_intentos: ZcIntentos;
  zc_opciones: ZcOpciones;
  zc_preguntas: ZcPreguntas;
  zc_quizzes: ZcQuizzes;
  zc_recursos: ZcRecursos;
  zc_respuestas: ZcRespuestas;
  zc_rubric_calificaciones: ZcRubricCalificaciones;
  zc_rubric_criterios: ZcRubricCriterios;
  zc_rubrics: ZcRubrics;
}
